import { useEffect,useMemo,useState } from "react";
import { listAllReports } from "../../services/reportService";
import { createAnnouncement,createMaintenance,exportCsv,listAnnouncements,listAuditLogs,listMaintenance,type Announcement,type AuditEntry,type MaintenanceItem } from "../../services/operationsService";

const fmt = (v: any) => v?.toDate?.().toLocaleString?.() ?? (v instanceof Date ? v.toLocaleString() : "—");
const toMillis = (v: any): number => {
  if (typeof v?.toMillis === "function") return v.toMillis();
  if (v instanceof Date) return v.getTime();
  const parsed = typeof v === "string" || typeof v === "number" ? new Date(v).getTime() : NaN;
  return Number.isFinite(parsed) ? parsed : 0;
};
export function AdminOperationsPage(){
 const [reports,setReports]=useState<any[]>([]),[ann,setAnn]=useState<Announcement[]>([]),[maint,setMaint]=useState<MaintenanceItem[]>([]),[audit,setAudit]=useState<AuditEntry[]>([]),[tab,setTab]=useState("analytics"),[error,setError]=useState("");
 const [announcement,setAnnouncement]=useState({title:"",message:""});
 const [maintenance,setMaintenance]=useState({title:"",location:"",frequency:"monthly",nextDue:"",notes:""});
 async function load(){try{const [r,a,m,l]=await Promise.all([listAllReports(),listAnnouncements(),listMaintenance(),listAuditLogs()]);setReports(r);setAnn(a);setMaint(m);setAudit(l);}catch(e){setError(e instanceof Error?e.message:"Unable to load operations.");}}
 useEffect(()=>{load()},[]);
 const active=reports.filter(r=>!["completed","closed","rejected"].includes(r.status));
 const resolved=reports.filter(r=>["completed","closed"].includes(r.status));
 const avg=useMemo(()=>{const values=reports.filter(r=>r.createdAt&&r.resolution?.completedAt).map(r=>(toMillis(r.resolution.completedAt)-toMillis(r.createdAt))/3600000).filter((v)=>Number.isFinite(v)&&v>=0);return values.length?Math.round(values.reduce((a,b)=>a+b,0)/values.length):0},[reports]);
 const category=useMemo<Array<[string, number]>>(()=>{const counts:Record<string,number>={};for(const r of reports){const name=String(r.departmentName??"Unknown");counts[name]=(counts[name]??0)+1;}return Object.entries(counts).sort((a,b)=>b[1]-a[1]);},[reports]);
 async function publish(){if(!announcement.title.trim()||!announcement.message.trim())return;await createAnnouncement({title:announcement.title.trim(),message:announcement.message.trim(),audience:"all",towerId:null,startsAt:new Date(),expiresAt:null,isActive:true,createdBy:"admin",createdByName:"CampusFix Admin"});setAnnouncement({title:"",message:""});await load();}
 async function schedule(){if(!maintenance.title||!maintenance.location||!maintenance.nextDue)return;await createMaintenance({title:maintenance.title,location:maintenance.location,frequency:maintenance.frequency as any,nextDue:new Date(maintenance.nextDue),isActive:true,notes:maintenance.notes});setMaintenance({title:"",location:"",frequency:"monthly",nextDue:"",notes:""});await load();}
 return <div><div className="page-header"><h1>Campus Operations</h1><p>Analytics, communication, preventive maintenance and audit history in one place.</p></div>{error&&<div className="alert alert--error">{error}</div>}
 <div className="tabs" style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:20}}>{["analytics","announcements","maintenance","audit"].map(x=><button key={x} className={`btn ${tab===x?"btn--primary":"btn--secondary"}`} onClick={()=>setTab(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div>
 {tab==="analytics"&&<><div className="stat-grid"><div className="stat-card"><div className="stat-card__value">{reports.length}</div><div className="stat-card__label">Total complaints</div></div><div className="stat-card"><div className="stat-card__value">{active.length}</div><div className="stat-card__label">Active</div></div><div className="stat-card"><div className="stat-card__value">{resolved.length}</div><div className="stat-card__label">Resolved / closed</div></div><div className="stat-card"><div className="stat-card__value">{avg?`${avg}h`:"—"}</div><div className="stat-card__label">Average resolution time</div></div></div><div className="card"><h2>Complaints by department</h2>{category.length?<div className="list-stack">{category.map(([name,count])=><div className="list-row" key={name}><span>{name}</span><strong>{count}</strong></div>)}</div>:<p>No complaint data yet.</p>}<button className="btn btn--secondary" style={{marginTop:16}} onClick={()=>exportCsv("campusfix-complaints.csv",reports.map(r=>({id:r.id,title:r.title,status:r.status,priority:r.priority,tower:r.towerName,department:r.departmentName,created:fmt(r.createdAt)})))}>Export CSV</button></div></>}
 {tab==="announcements"&&<><div className="card"><h2>Publish announcement</h2><input className="input" placeholder="Title" value={announcement.title} onChange={e=>setAnnouncement({...announcement,title:e.target.value})}/><textarea className="input" rows={4} placeholder="Message" value={announcement.message} onChange={e=>setAnnouncement({...announcement,message:e.target.value})}/><button className="btn btn--primary" onClick={publish}>Publish to campus</button></div><div className="card"><h2>Recent announcements</h2>{ann.map(a=><div className="list-row" key={a.id}><div><strong>{a.title}</strong><div>{a.message}</div></div><small>{fmt(a.createdAt)}</small></div>)}</div></>}
 {tab==="maintenance"&&<><div className="card"><h2>Preventive maintenance</h2><input className="input" placeholder="Equipment / task" value={maintenance.title} onChange={e=>setMaintenance({...maintenance,title:e.target.value})}/><input className="input" placeholder="Location" value={maintenance.location} onChange={e=>setMaintenance({...maintenance,location:e.target.value})}/><select className="input" value={maintenance.frequency} onChange={e=>setMaintenance({...maintenance,frequency:e.target.value})}><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="half_yearly">Half-yearly</option><option value="yearly">Yearly</option></select><input className="input" type="date" value={maintenance.nextDue} onChange={e=>setMaintenance({...maintenance,nextDue:e.target.value})}/><textarea className="input" placeholder="Notes" value={maintenance.notes} onChange={e=>setMaintenance({...maintenance,notes:e.target.value})}/><button className="btn btn--primary" onClick={schedule}>Schedule maintenance</button></div><div className="card"><h2>Schedule</h2>{maint.map(m=><div className="list-row" key={m.id}><div><strong>{m.title}</strong><div>{m.location} · {m.frequency}</div></div><strong>{fmt(m.nextDue)}</strong></div>)}</div></>}
 {tab==="audit"&&<div className="card"><h2>Audit history</h2>{audit.length?audit.map(a=><div className="list-row" key={a.id}><div><strong>{a.action}</strong><div>{a.summary}</div></div><small>{a.actorName} · {fmt(a.createdAt)}</small></div>):<p>No audit entries yet. New operational modules will record activity here.</p>}</div>}
 </div>
}
